# Multi-stage Dockerfile for calliope — bun MCP star on stellar_core:bun-mcp.
# The base is FROM oven/bun + the Pistis stellar-boot chain; its ENTRYPOINT is
# stellar-boot, which execs this CMD (dormant until CALYPSO_IDENTITY_ID is set).
# Generated by the frontend-repo copier template (framework=mcp).
#
# The base is DIGEST-PINNED, not tracked by tag: the shared build runs a plain
# `docker build` (no --pull), so a floating tag resolves to whatever the runner
# happens to have cached — the base a build lands on stops being a property of
# this repo. Bump the digest deliberately; a bump is a base migration.

# -- Stage 1: builder (bun) ---------------------------------------------------
FROM forgejo.notusmi.com/rob/stellar_core:bun-mcp@sha256:a8d21e4ae94191e03d7d83f23f8456c60122163c4345d4d3b215074a2a533b91 AS builder
ENV CI=1
WORKDIR /app
COPY . /app
RUN --mount=type=cache,id=bun,target=/root/.bun/install/cache \
    bun install --frozen-lockfile
# Bundle the streamable-HTTP entry + deps into ONE bun-target file (no
# node_modules shipped — smaller image + CVE surface). The monorepo roots the
# entry at apps/calliope/src/mcp/http.ts.
RUN bun build apps/calliope/src/mcp/http.ts --target=bun --outfile /deploy/server.js --minify

# -- Stage 2: runtime ---------------------------------------------------------
FROM forgejo.notusmi.com/rob/stellar_core:bun-mcp@sha256:a8d21e4ae94191e03d7d83f23f8456c60122163c4345d4d3b215074a2a533b91
WORKDIR /app
COPY --from=builder --chown=bun:bun /deploy/server.js ./server.js
ENV NODE_ENV=production HOST=0.0.0.0 PORT=8204
USER bun
EXPOSE 8204
# Liveness — the base has bun (no curl); a GET /mcp answers 405 (POST-only),
# which still proves the HTTP server is up; only a connect failure fails.
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
    CMD bun -e "fetch('http://127.0.0.1:'+(process.env.PORT||8204)+'/mcp').then(function(r){process.exit(r.status?0:1)}).catch(function(){process.exit(1)})"
CMD ["bun", "server.js"]
